export const mfConfig = {
  name: "html_container",
  remotes: {
    // htmlCssTestApp: "htmlCssTestApp@http://localhost:3001/remoteEntry.js",
    // javascriptTestApp: "javascriptTestApp@http://localhost:3002/remoteEntry.js",
    // kakaoAuthenticationApp: "kakaoAuthenticationApp@http://localhost:3003/remoteEntry.js",
    // vuetifyTailwindBoardApp: "vuetifyTailwindBoardApp@http://localhost:3004/remoteEntry.js",
    // navigationBarApp: "navigationBarApp@http://localhost:3005/remoteEntry.js",
    // reactTestApp: "reactTestApp@http://localhost:3006/remoteEntry.js",
    // googleAuthenticationApp: "googleAuthenticationApp@http://localhost:3100/remoteEntry.js",
    // recoilBoardApp: "recoilBoardApp@http://localhost:3101/remoteEntry.js",
    // vtestApp: `vtestApp@${process.env.VTEST_APP}/remoteEntry.js`,
    navigationBarApp: `navigationBarApp@${process.env.REACT_NAVIGATION_APP}/remoteEntry.js`,
    vueBoardApp: `vueBoardApp@${process.env.VUE_BOARD_APP}/remoteEntry.js`,
    diceGameApp: `diceGameApp@${process.env.SVELTE_DICE_GAME_APP}/remoteEntry.js`,
    authenticationApp: `authenticationApp@${process.env.AUTHENTICATION_APP}/remoteEntry.js`,
    gameChipApp: `gameChipApp@${process.env.VUE_GAME_CHIP_APP}/remoteEntry.js`,
    cartApp: `cartApp@${process.env.REACT_CART_APP}/remoteEntry.js`,
    laptopApp: `laptopApp@${process.env.VUE_LAPTOP_APP}/remoteEntry.js`,
  },
  shared: {
    react: { singleton: true, requiredVersion: "^18.2.0" },
    "react-dom": { singleton: true, requiredVersion: "^18.2.0" },
    "@mui/material": { singleton: true, requiredVersion: "^7.0.1" },
    "@mui/icons-material": { singleton: true, requiredVersion: "^7.0.1" },
    "react-router-dom": { singleton: true, requiredVersion: "^6.30.0" },
    three: { singleton: true, requiredVersion: "^0.177.0", },
  },
};